workspace = "/data/rcnp2025/brill"
trigger = "main"
jump_run = [1034, 1041, 1052, 1053, 1054, 1055, 1061, 1062, 1063, 1064, 1065, 1066, 1067, 1068, 1069, 1070, 1071, 1086, 1087, 1090, 1124]
assets = "assets"

[paths]
ore = "trace"
grit = "grit"
ingot = "ingot"
normalize = "normalize"
match = "match"
telescope = "telescope"
particle = "particle"
spectrum = "spectrum"
estimate = "estimate"

[t0]
silicon = ["t0d1", "t0d2"]

[detectors.ppac]
z_mm = [-52.0, -332.0, -612.0]
x_offset_mm = [0.0, 0.0, 0.0]
y_offset_mm = [0.0, 0.0, 0.0]
x_scale = [1.0, 1.0, 1.0]
y_scale = [1.0, 1.0, 1.0]

[detectors.t0d1]
type = "dssd"
front_strips = 128
back_strips = 128
thickness_um = 500.0
size_x_mm = 97.22
size_y_mm = 97.22
center_x_mm = 0.0
center_y_mm = 0.0
z_mm = 1500.0
match_tolerance = 2000.0
use_integral = true

[detectors.t0d2]
type = "dssd"
front_strips = 128
back_strips = 128
thickness_um = 1000.0
size_x_mm = 97.22
size_y_mm = 97.22
center_x_mm = 0.0
center_y_mm = 0.0
z_mm = 1500.0
match_tolerance = 2000.0
use_integral = true

[[normalize.run]]
run = 1024
use = 1024

[[normalize.t0d1.strips]]
index = 0
norm_side = 0
ref = [45, 45]
norm = [97, 111]
ref_energy = [0.0, 60000.0]
norm_energy = [0.0, 60000.0]

[[normalize.t0d1.strips]]
index = 1
norm_side = 1
ref = [97, 111]
norm = [29, 75]
ref_energy = [0.0, 60000.0]
norm_energy = [0.0, 60000.0]

[[normalize.t0d1.strips]]
index = 2
norm_side = 0
ref = [29, 75]
norm = [0, 127]
ref_energy = [0.0, 60000.0]
norm_energy = [0.0, 60000.0]

[[normalize.t0d1.strips]]
index = 3
norm_side = 1
ref = [0, 127]
norm = [0, 127]
ref_energy = [0.0, 60000.0]
norm_energy = [0.0, 60000.0]

[[normalize.t0d2.strips]]
index = 0
norm_side = 0
ref = [46, 46]
norm = [101, 109]
ref_energy = [1000.0, 85000.0]
norm_energy = [1000.0, 85000.0]

[[normalize.t0d2.strips]]
index = 1
norm_side = 1
ref = [101, 109]
norm = [34, 67]
ref_energy = [1000.0, 85000.0]
norm_energy = [1000.0, 85000.0]

[[normalize.t0d2.strips]]
index = 2
norm_side = 0
ref = [34, 67]
norm = [0, 127]
ref_energy = [1000.0, 85000.0]
norm_energy = [1000.0, 85000.0]

[[normalize.t0d2.strips]]
index = 3
norm_side = 1
ref = [0, 127]
norm = [0, 127]
ref_energy = [1000.0, 85000.0]
norm_energy = [1000.0, 85000.0]

[track]
d2d1_window = [-4.0, 2.0]

[identify.straight.t0d1d2]
A = 0.1075
B = -0.0744
[[identify.straight.t0d1d2.particles]]
particle = "4He"
mean = 4060.3
sigma = 139.5
range = 2.0
